PS1='\[\e[0;33m\]\h\[\e[m\] [\[\e[0;32m\]\u\[\e[m\] \[\e[0;34m\]\w\[\e[m\]] $ '

# add all unencrypted keys to the ssh agent.
#
# encrypted keys would aks for passphrase and block therefore.
# you will have to add encrypted keys yourself or add them to the keychain if 
# you are running osx
#
SSH_KEYS=$(grep -L ENCRYPTED ~/.ssh/*rsa)
for key in $SSH_KEYS; do
    ssh-add $key &> /dev/null
done
