" show line numbers
set number

" one tab is equals four spaces
set tabstop=4

" TODO
set expandtab

" TODO
set autoindent

" highlight search results
set hlsearch

" search as you type
set incsearch

" case insensitive search
set ignorecase

" enable syntax highlighting
syntax on
